Better limelight
DeepBlueRobotics/lib199 pull request #18
Opened 2021-10-15 23:48 UTC by Sean-Weber

Removed Smartdashboard from Limelight.java, and created a Config and Debug class that allows Limelight.java to be changed by Robot Code (Through config) and to get values from Limelight.java (Through debugInfo).

2021-10-16 00:07 UTC, CoolSpy3 approved these changes

2021-10-16 00:07 UTC, 0sani approved these changes

2021-10-16 20:16 UTC, brettle requested changes

2021-10-16 20:16 UTC, brettle commented on src/main/java/frc/robot/lib/Limelight.java
> +        pidController = new PIDController(pidValues[0], pidValues[1], pidValues[2], 1.0 / 90.0);
The magic 1.0/90.0 belongs in the `Config`. Incidentally, the value doesn't seem right to me, since I'd expect it to be the default `TimedRobot` period of 0.02s, but maybe I'm missing something.

2021-10-16 20:16 UTC, brettle commented on src/main/java/frc/robot/lib/Limelight.java
> +        public double kP = 0.225;
These need much clearer names, ideally including units where appropriate, and documentation regarding what they do. Note that there are effectively 2 different proportional constants, as well as `area_threshold` and and `areaThreshold`.

2021-10-16 20:16 UTC, brettle commented on src/main/java/frc/robot/lib/Limelight.java
> +        public double ballForward = 0;
Since the goal is to reuse `lib199` for different years and there might not be balls some years, the word `ball` shouldn't appear in the API.

The names should also specify units and their meaning/interpretation should be documented.

2021-10-16 20:16 UTC, brettle commented on src/main/java/frc/robot/lib/Limelight.java
> +        public double adjustment = 0;
Include units and document meaning/interpretation.

2021-10-20 22:58 UTC, brettle requested changes

2021-10-20 22:58 UTC, brettle commented on src/main/java/frc/robot/lib/Limelight.java
> +      public double backlashSteeringOffset = 0.0;
Units?

2021-10-20 22:58 UTC, brettle commented on src/main/java/frc/robot/lib/Limelight.java
> +       * Steering factor for adjustment
What exactly is this?

2021-10-21 00:35 UTC, merged