Robot path dev
DeepBlueRobotics/lib199 pull request #19
Opened 2021-10-16 00:08 UTC by 0sani

Added RobotPath.java to lib199 and added Interface for Drivetrain

2021-10-16 19:13 UTC, CoolSpy3 commented
I'm working on an update to move some of the removed functionality into new interfaces. I've marked this as a draft until that change is pushed.

2021-10-16 20:43 UTC, brettle requested changes
Since this will now be part of a library that we intend to reuse in future years, all public classes, interfaces, and methods should be documented.

2021-10-16 20:43 UTC, brettle commented on src/main/java/frc/robot/lib/Utils199.java
> +}
Consider using this instead: https://docs.oracle.com/javase/8/docs/api/java/util/stream/DoubleStream.html#average--

2021-10-16 20:43 UTC, brettle commented on src/main/java/frc/robot/lib/path/DrivetrainInterface.java
> +
Include units in names.

2021-10-20 23:40 UTC, brettle requested changes

2021-10-20 23:40 UTC, brettle commented on src/main/java/frc/robot/lib/path/SwerveDriveInterface.java
> +    public default Command createRamseteCommand(Trajectory trajectory, Supplier<Rotation2d> desiredHeading) {
Since this doesn't return a `RamseteCommand`, it should be renamed. Consider using `createAutoCommand` instead.

2021-10-20 23:40 UTC, brettle commented on src/main/java/frc/robot/lib/path/RobotPath.java
> +    public void generateTrajectory() {
Does this need to be public?

2021-10-20 23:40 UTC, brettle commented on src/main/java/frc/robot/lib/path/RobotPath.java
> +    }
This seems unnecessarily confusing. First, the `DrivetrainInterface` has a method with the same name which does something different. Second, if the goal is to allow the `TrajectoryConfig` to be modified (e.g. add constraints), why not just have a method `getTrajectoryConfig()` that returns the config for the path?

2021-10-20 23:40 UTC, brettle commented on src/main/java/frc/robot/lib/path/SwerveDriveInterface.java
> +    public void autoDrive(SwerveModuleState[] swerveModuleStates);
This doesn't need to be auto-specific, does it?

2021-10-20 23:40 UTC, brettle commented on src/main/java/frc/robot/lib/path/DifferentialDriveInterface.java
> +    public void autoDrive(double left, double right);
This doesn't need to be auto-specific, does it?

2021-10-20 23:40 UTC, brettle commented on src/main/java/frc/robot/lib/path/DrivetrainInterface.java
> +    public double getAutoMaxSpeedMps();
These aren't auto-specific, per-se. To the degree they are, we might want to use different values for different paths. Recommend, removing "auto" from the names here and providing a way (in `RobotPath`) to change the values used for a path before it is generated.

2021-10-20 23:40 UTC, brettle commented on src/main/java/frc/robot/lib/path/DifferentialDriveInterface.java
> +    public double getAutoMaxVolt();
See my comments about `DrivetrainInterface.getAuto*()` methods. They apply here as well.

2021-10-25 23:59 UTC, merged