Remove logging support
DeepBlueRobotics/lib199 pull request #23
Opened 2022-05-09 00:08 UTC by CoolSpy3

[WPILib has released its own logging API](https://docs.wpilib.org/en/stable/docs/software/telemetry/datalog.html). It will likely be more efficient and better maintained than the one in lib199. As a result, the logging features present in lib199 are no longer necessary.

2022-05-09 02:36 UTC, brettle requested changes
Until all projects which use the lib199 logging support are either updated to use the wpilib logging support or are no longer needed (i.e. the associated robots no longer exist), I recommend marking the classes as deprecated instead of deleting them. That will allow those other projects to continue to work unchanged while also taking advantage of any unrelated future lib199 fixes/features.

See: https://stackoverflow.com/questions/20674135/deprecated-vs-deprecated

2022-05-09 05:59 UTC, CoolSpy3 commented
Okay, I'll create a new PR to deprecate the code.

2023-07-21 23:09 UTC, CoolSpy3 commented
I'm pretty sure that this condition is now met and we no longer have any active projects which use any of the logging classes. These have been deprecated for ~1 year and should be removed in the next major release.

2023-07-24 06:05 UTC, ProfessorAtomicManiac approved these changes

2024-05-15 02:13 UTC, brettle approved these changes

2024-05-15 02:13 UTC, merged