Fix Sparatic Temperature Reporting
DeepBlueRobotics/lib199 pull request #41
Opened 2023-04-02 05:57 UTC by CoolSpy3

2023-04-02 06:06 UTC, brettle requested changes

2023-04-02 06:06 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
> +                    overheatedSparks.put(port, kOverheatTripCount + 1);
Why is this line needed?

2023-04-02 06:11 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
> +                    overheatedSparks.put(port, kOverheatTripCount + 1);
The idea is that we want to print an error message to the log. At the same time, we don't want to constantly print error messages to avoid further cluttering the logs. To avoid creating yet another HashMap to store whether we've logged a message, my solution was to set the trip count to one more than the number required to be considered overheated.

If the SparkMax is newly considered overheated, numTrips = kOverheeatTripCount, we print a message and set the trip count to one more than the overheat trip count to flag that it's been printed.

2023-04-02 06:16 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
> +                    overheatedSparks.put(port, kOverheatTripCount + 1);
I see. Please add a comment to that effect.

2023-04-02 06:35 UTC, brettle reviewed
Looks good but recommend waiting on this until after comp. Note that your fix only addresses sporadic temp reporting. If the temp sensor is broken in a way that causes it to consistently report a false high temp, the motor will still be shut down. Since the 2023 bot still has a motor with a questionable temp sensor on it, this remains a risky change.

2023-04-02 06:44 UTC, CoolSpy3 commented
> Looks good but recommend waiting on this until after comp. Note that your fix only addresses sporadic temp reporting. If the temp sensor is broken in a way that causes it to consistently report a false high temp, the motor will still be shut down. Since the 2023 bot still has a motor with a questionable temp sensor on it, this remains a risky change.

I'm fine to wait until after comp. In my opinion, a motor with a faulty temp sensor should be disabled because 1) we cannot safely ensure it stays in a safe temperature range, and 2) If the temp sensor is broken, it's not improbable that there is damage to the motor or encoder as well.

2023-05-07 01:38 UTC, ProfessorAtomicManiac requested changes

2023-05-07 01:38 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
> +    public static final int kOverheatTripCount = 5;
assuming that the trips are being checked every robot periodic call, do the motors report erroneous values for just 5 * 0.2ms (I don't remember the exact cycle time)?

2023-05-07 01:38 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
>                      System.err.println("Port " + port + " spark max is operating at " + temp + " degrees Celsius! It will be disabled until the robot code is restarted.");
can we like make the error more obvious than a `System.err.println()`? Looking through driver station logs is very annoying. How were you guys able to find the error when testing the arm back then?

2023-05-07 01:38 UTC, ProfessorAtomicManiac commented on src/test/java/org/carlmontrobotics/lib199/MotorErrorsTest.java
>          assertEquals(1, spark.getSmartCurrentLimit());
you might want to test trying to change the current limit and making sure that the program sets it back to 1

2023-05-07 01:38 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
>                  spark.setSmartCurrentLimit(1);
why not `spark.disable()`?

2023-05-07 01:38 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/MotorConfig.java
Units for temperaturelimit and currentlimit would be good (ive become pretty strict on units after wasting hours debugging smth only to find out I was using radians instead of degrees lol). Also github won't let me comment on code you didn't change so you might not see the exact line but it should be close enough.

2023-05-07 01:44 UTC, ProfessorAtomicManiac commented on src/test/java/org/carlmontrobotics/lib199/MotorErrorsTest.java
>          assertEquals(20, SmartDashboard.getNumber(smartDashboardKey, 0), 0.01);
why do we use smartdashboard instead of using the `TemperatureSparkMax` interface?

2023-05-07 08:20 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
> +    public static final int kOverheatTripCount = 5;
I just picked 5 because it seemed like a good number. Based on #37, I believe that the erroneous values probably only appear for a single cycle (20ms)

2023-05-07 08:20 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
>                      System.err.println("Port " + port + " spark max is operating at " + temp + " degrees Celsius! It will be disabled until the robot code is restarted.");
I'm not sure. Where else do you think we should display the error? @brettle found the arm error using DS logs (see #37)

2023-05-07 08:20 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/MotorErrorsTest.java
>          assertEquals(1, spark.getSmartCurrentLimit());
Good idea! Done!

2023-05-07 08:20 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
>                  spark.setSmartCurrentLimit(1);
`spark.disable()` just calls `set(0)` it doesn't actually disable the motor :( We could do `spark.close()`, but that would just throw an `IllegalStateException` any time we tried to call methods on it.

2023-05-07 08:21 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorConfig.java
Done!

2023-05-07 08:21 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/MotorErrorsTest.java
>          assertEquals(20, SmartDashboard.getNumber(smartDashboardKey, 0), 0.01);
The `TemperatureSparkMax` interface is just a helper class for the tests. That `assertEquals` is supposed to check that `MotorErrors` is logging the correct temperature to Smart Dashboard.

2023-05-07 19:28 UTC, ProfessorAtomicManiac approved these changes
Everything looks good to me! Just gotta test it. I'm assuming you can just run `Test Robot Code` in lib199, but you intend to do other tests?

2023-05-07 19:28 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
>                      System.err.println("Port " + port + " spark max is operating at " + temp + " degrees Celsius! It will be disabled until the robot code is restarted.");
might be a good feature for your GUI :)

2023-05-07 19:31 UTC, CoolSpy3 commented
> Everything looks good to me! Just gotta test it. I'm assuming you can just run `Test Robot Code` in lib199, but you intend to do other tests?

 We probably should test on the actual robot to see if it fixes the arm problem.

2023-05-07 19:33 UTC, CoolSpy3 commented
>Having something that records these kinds of errors in an organized manner instead of spiting them to Driver Logs might be a good feature for your GUI :)

Careful. You'll give me ideas ;P

2023-06-30 00:36 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorErrors.java
>                      System.err.println("Port " + port + " spark max is operating at " + temp + " degrees Celsius! It will be disabled until the robot code is restarted.");
Moved to DeepBlueRobotics/CommandVisualizerClient#1

2023-07-09 06:17 UTC, merged