Remove SparkMax Unplugged Handler and Deprecate Related Methods
DeepBlueRobotics/lib199 pull request #48
Opened 2023-05-26 23:30 UTC by CoolSpy3

Fixes #45 .

2023-06-29 20:54 UTC, FriedLongJohns submitted a review, later dismissed
Looks fine to me from what I can understand, as long as people know that revRobotics has code for this instead of lib199

2023-06-29 22:32 UTC, ProfessorAtomicManiac requested changes

2023-06-29 22:32 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/MotorControllerFactory.java
>        spark = new CachedSparkMax(id, CANSparkMaxLowLevel.MotorType.kBrushless);
aren't we trying to deprecate CachedSparkMax?

2023-06-29 22:33 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorControllerFactory.java
>        spark = new CachedSparkMax(id, CANSparkMaxLowLevel.MotorType.kBrushless);
That's a separate PR from this one. Once they are both merged, the final result will not include `CachedSparkMax`.

2023-07-05 21:17 UTC, ProfessorAtomicManiac submitted a review, later dismissed

2023-07-06 04:55 UTC, merged