Update fake PWM ports to increment their values by 10
DeepBlueRobotics/lib199 pull request #5
Opened 2020-12-26 19:31 UTC by CoolSpy3

Fixes #4.

2020-12-26 19:37 UTC, brettle requested changes
Looks like with an expansion board there can be up to 20 regular PWM channels. See:

https://first.wpi.edu/FRC/roborio/release/docs/java/edu/wpi/first/wpilibj/PWMSpeedController.html#%3Cinit%3E(int)

2020-12-26 19:42 UTC, CoolSpy3 commented
It looks like `EncoderSim` caps its input values between 0 and 20 :/

2020-12-26 19:56 UTC, brettle commented
> It looks like `EncoderSim` caps its input values between 0 and 20 :/

Grumble. Can we use a SimDeviceSim instead?

2020-12-26 19:59 UTC, CoolSpy3 commented
> > It looks like `EncoderSim` caps its input values between 0 and 20 :/
> 
> Grumble. Can we use a SimDeviceSim instead?

I'll look into it.

2020-12-26 23:02 UTC, CoolSpy3 commented
This is supplemented by https://github.com/DeepBlueRobotics/WPILibWebSocketsToWebots/pull/10

2020-12-27 00:33 UTC, brettle approved these changes
Nice! Just the one suggestion. If that's all you change, no further approval needed.

2020-12-27 00:33 UTC, brettle commented on src/main/java/frc/robot/lib/sim/MockedSparkEncoder.java
> +        device = SimDevice.create("EncoderSim_SparkMax", id);
Since the other devices don't have "Sim" in their names, I recommend using "CANEncoder_SparkMax".

Side note: Resist the temptation to just use "CANEncoder". My understanding it that technically speaking, two different types of devices can be configure to have the same ID and they will not interfere with each other. Only the combination of device type and CAN ID needs to be unique. So including "_SparkMax" allows use to support that.

2020-12-27 00:44 UTC, merged