Create `SensorFactory`
DeepBlueRobotics/lib199 pull request #55
Opened 2023-06-29 23:14 UTC by CoolSpy3

Moves some methods from `MotorControllerFactory` to a new `SensorFactory` class

2023-07-08 18:37 UTC, ProfessorAtomicManiac approved these changes

2023-07-08 18:39 UTC, ProfessorAtomicManiac commented
Perhaps to make it not a breaking change you can deprecate the methods in MotorControllerFactory.java so older projects will still work

2023-07-08 18:49 UTC, ProfessorAtomicManiac requested changes

2023-07-08 18:49 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/MotorControllerFactory.java
> -  }
See my previous comment

2023-07-09 05:45 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/MotorControllerFactory.java
> -  }
Done! But I think I still want to remove the methods before the next major release. That can be another PR though.

2023-07-18 03:28 UTC, ProfessorAtomicManiac approved these changes

2023-07-18 06:02 UTC, merged