Smart numbers
DeepBlueRobotics/lib199 pull request #65
Opened 2023-08-09 23:28 UTC by TuskAct2

adds SmartNumber along with SmartBoolean and SmartString code and completed test code as a replacement for the smart dashboard methods

2023-08-11 06:25 UTC, CoolSpy3 requested changes
Good start! You have a lot of the basic code, but I think it could be more feature-rich.

Firstly, you'll notice I pushed a commit labeled "formatting". This is just a bunch of formatting changes which would've been superfluous to address in the comments. A basic summary:
* This codebase typically uses [K&R rather than Allman](https://en.wikipedia.org/wiki/Indentation_style) indentation style, so I updated the code to match that.
* Added/removed blank lines to divide everything (typically a newline after the class definition and between functions. Other newlines added where it makes sense.)
* Ran `Trailing Spaces: Delete`
* Ran `Organize Imports`

**The other suggestions:**
These files should all be moved to a new package and have Javadocs written for them.

Because a lot of this code is very similar, I've primarily written comments for the boolean code, but they should be extended to the other classes where applicable.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
> +    private final boolean userValue;
Make it clear that this is the default value.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
Add a method to fire a callback when the value changes. Something like `onChanged(BooleanConsumer callback)`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
> +    public void set(Boolean userValue) {
Use the primitive boolean type.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
> +    public Boolean getValue() {
Make it clear that this is getting the default value.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
> +    public Boolean getValue() {
Use the primitive boolean type.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
Add a method to retrieve the current value of the entry. I'd recommend just calling it `get()`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
Implement `AutoCloseable`, and map the `close()` method to `entry.close()`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartBooleanTest.java
> +    SmartBoolean wingMan = new SmartBoolean("Goober", true);
I'm somewhat concerned that all the `SmartX` instances are created with the name "Goober". I'd recommend using different names so that SmartDashboard doesn't run into any weird conflicts. I'd also recommend creating a different instance (with a different name) for each test to avoid any synchronization bugs/race conditions. They should be created in a [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) block which wraps each test. (See above note about implementing `AutoCloseable`.)

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartBooleanTest.java
> +    public void testGetUserValue() {
Make it clear that this is getting the default value. I'd recommend attempting to change the value within the test to ensure that it is always getting the default.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartBooleanTest.java
> +        assertFalse(false);
This is a no-op. You want `assertFalse(wingMan.get());`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartBooleanTest.java
> +        assertFalse(false);
This is a no-op. You want `assertFalse(wingMan.get());`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartNumberTest.java
> +        assertEquals(mosh.getValue(), 2.2, 2.2);
Use a smaller delta. I think you meant `assertEquals(mosh.getValue(), 2.2, 0.001);`

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartNumberTest.java
> +        assertEquals(0, 0, 0.001);
This is a no-op. I think you meant `assertEquals(mosh.get(), 4, 0.001);`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartStringTest.java
> +        assertEquals(dizzy.getValue(), "blue", "blue");
This is a no-op. It will check if `"blue".equals("blue")`, and print `dizzy.getValue()` if it's not. I think you meant `assertEquals(dizzy.getValue(), "blue");`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartStringTest.java
> +        assertEquals("splat", "splat");
This is a no-op. I think you meant `assertEquals(dizzy.get(), "splat");`.

2023-08-11 06:25 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/SmartStringTest.java
> +        assertEquals("", "");
This is a no-op. I think you meant `assertEquals(dizzy.get(), "blue");`.

2023-08-11 19:41 UTC, ProfessorAtomicManiac reviewed
Ryan covered all of my comments so fix those

2023-08-11 19:41 UTC, ProfessorAtomicManiac commented on src/main/java/org/carlmontrobotics/lib199/SmartBoolean.java
> +    public Boolean getValue() {
technically if the value changes its not default anymore right?

2023-08-11 19:41 UTC, ProfessorAtomicManiac commented on src/test/java/org/carlmontrobotics/lib199/SmartBooleanTest.java
> +    SmartBoolean wingMan = new SmartBoolean("Goober", true);
we don't really talk about interfaces such as `AutoCloseable` in programming training. Maybe we should add those?

2024-05-14 18:39 UTC, brettle commented
1. Shouldn't the `get()` methods return the values currently in NetworkTables, not the value passed to the constructor? Note that the user could have changed the value in NetworkTables via SmartDashboard.

2. `userValue` is not a particularly meaningful variable name. Seems like it should be something like `initialValue`.

3. Does this PR offer significant advantages over adding lines like the following to the appropriate `initSendable()` method for each new SmartDashboard value?

```
builder.addDoubleProperty("Name", () -> field, newValue -> { field = newValue });
```

Do those advantages outweigh the effort associated with implementing, maintaining, and training programmers on the use of these classes?

2024-05-27 02:54 UTC, brettle commented
After discussion with @CoolSpy3 @ProfessorAtomicManiac and @FriedLongJohns, we decided to abort this branch in favor of using [`initSendable()`](https://docs.wpilib.org/en/stable/docs/software/telemetry/writing-sendable-classes.html) whenever possible.

The last commit on this branch can be retrieved via the [`aborted-SmartNumbers-attempt`](https://github.com/DeepBlueRobotics/lib199/tree/aborted-SmartNumbers-attempt) tag.

2024-05-27 02:54 UTC, closed without merging