Use spec compliant names for devices and data to fix issue #93.
DeepBlueRobotics/lib199 pull request #94
Opened 2024-05-21 19:26 UTC by brettle

fix #93

2024-05-24 04:37 UTC, CoolSpy3 requested changes

2024-05-24 04:37 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java
> +        init = device.createBoolean("init", Direction.kOutput, true);
`CANDutyCycle` does not have an `"init"` value. It does have a `"connected"` value, but that's an input rather than an output.

2024-05-24 04:37 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java
> +        init = device.createBoolean("init", Direction.kOutput, true);
Because this value is only used for `CANAIn` devices, it could be gated behind the above `analog` check. Although, given that we are allowed to transmit additional data values, it might just add more complexity without much benefit (given we'd also need an additional check in `close()`).

2024-05-24 04:37 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java
> -        return velocity.get() * (inverted ? -1 : 1) * velocityConversionFactor / countsOrVoltsPerRev;
I just noticed that there needs to be a difference in implementations here. `AbsoluteEncoder` returns velocities in rps, and `RelativeEncoder` uses rpm.

Also note that `velocity` does not exist for `CANDutyCycle` objects. We could transmit it as an additional value, but as of DeepBlueRobotics/WPIWebSockets#34, that functionality is no longer directly exposed.

2024-05-24 04:37 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedMotorBase.java
> +        init = device.createBoolean("init", Direction.kOutput, true);
`CANMotor` does not have an `"init"` value.

Additionally, we should add support for `"busVoltage"` and use it to replace `defaultNominalVoltage`.

2024-05-24 04:37 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlight.java
> +        rangeDevice = SimDevice.create("CANAIn:PlayingWithFusionTimeOfFlight[%d]-rangeVoltsIsMM".formatted(port));
Off-topic, but do you think it would be worth opening a pr to add a `SimDeviceSim.create(String, int, String)` method to support this device name format?

2024-05-24 04:37 UTC, CoolSpy3 commented on src/main/java/org/carlmontrobotics/lib199/swerve/SwerveModuleSim.java
>          this.turnInversion = turnInversion;
It looks like `driveInversion`, `turnGearing`, and `turnInversion` are unused. Is this intentional?

2024-05-24 04:37 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java
> +            func.test((TimeOfFlight)dev, rangeDeviceSim, ambientLightLevelDeviceSim);
Unnecessary cast to `TimeOfFlight`.

2024-05-24 04:37 UTC, CoolSpy3 commented on src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java
>      }
`EncoderTest` and `encoder` should probably be renamed.

2024-05-24 20:28 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java
> +        device = SimDevice.create("CANDutyCycle:CANCoder", port);
Would prefer to handle in a separate PR if it is needed.

2024-05-24 20:31 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java
> +        init = device.createBoolean("init", Direction.kOutput, true);
Inclined to leave it for simplicity.

2024-05-24 20:37 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlight.java
> +        rangeDevice = SimDevice.create("CANAIn:PlayingWithFusionTimeOfFlight[%d]-rangeVoltsIsMM".formatted(port));
No objections, but not a high priority either.

2024-05-24 20:51 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/swerve/SwerveModuleSim.java
>          this.turnInversion = turnInversion;
`driveInversion` and `turnInversion` are not needed here because they should be set correctly on the respective motors.
The `turnGearing` passed to the constructor is used to create an accurate sim of the turn physics (`turnPhysicsSim`), but is not used outside the constructor. I'm removing the other references.

2024-05-24 21:08 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedEncoder.java
> -        return velocity.get() * (inverted ? -1 : 1) * velocityConversionFactor / countsOrVoltsPerRev;
For now, I'm going to address the different units with an anonymous subclass that overrides `getVelocity()` when we create an absolute encoder.

Also for now I'm ok with velocity not working with DeepBlueSim/WPIWebSockets. At least this way it can work with other simulators.

2024-05-24 21:10 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockSparkBase.java
> +            encoder = new MockedEncoder(SimDevice.create("CANEncoder:%s[%d]".formatted(name, port)), countsPerRev, false, false) {
Now fixed.

2024-05-24 21:10 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockSparkBase.java
> +    public MockSparkBase(int port, MotorType type, String name, int countsPerRev) {
Now fixed.

2024-05-24 21:10 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java
>          gearing = device.createDouble("gearing", Direction.kOutput, 1);
Now fixed.

2024-05-24 21:11 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedCANCoder.java
> +        init = device.createBoolean("init", Direction.kOutput, true);
Now fixed.

2024-05-24 21:11 UTC, brettle commented on src/main/java/org/carlmontrobotics/lib199/sim/MockedMotorBase.java
> +        init = device.createBoolean("init", Direction.kOutput, true);
Now fixed.

2024-05-24 21:11 UTC, brettle commented on src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java
> +            func.test((TimeOfFlight)dev, rangeDeviceSim, ambientLightLevelDeviceSim);
Now fixed.

2024-05-24 21:11 UTC, brettle commented on src/test/java/org/carlmontrobotics/lib199/sim/MockedPlayingWithFusionTimeOfFlightTest.java
>      }
Now fixed.

2024-05-25 01:38 UTC, CoolSpy3 approved these changes

2024-05-25 01:39 UTC, merged